### ISSUE TITLE
Using custom rules in transform callback is not possible

### ISSUE THREAD

**Issue by kees-yesco** [selective-php/transformer#4] opened 2022-11-03 15:37 UTC
When you use custom rules inside a transform callback you get an exception 'Filter not found:...'

```
<?php
$transformer = new ArrayTransformer();
$transformer->registerFilter('lower', 'strtolower');

transformer->map('destination.elem', 'source.elem', $transformer->rule()->transform(
    function (ArrayTransformer $transformer) {
        $transformer->map('test1', 'xxx', 'integer')
            ->map('test2', 'yyy', 'lower');
    }
))
?>
```

The cause seems to be that ArrayTransformerRule::transform is using a new instance of ArrayTransformer instead of reusing the existing ArrayTransformer object.

Is it possible to fix this?

**Comment by odan** [comment] 2022-11-03 18:55
Thanks for reporting. I think the problem is here:

https://github.com/selective-php/transformer/blob/master/src/Filter/TransformFilter.php#L27

I'll take a closer look.

**Comment by odan** [comment] 2022-11-08 19:27
It should be fixed in the latest version.

**Closed as completed** 2022-11-09 13:39 UTC
